config/routes.rb
Rails.application.routes.draw do
  
  get :home, :form, :math, controller: :pages
  post :about, controller: :pages
  get :admin, controller: :admin 
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base

    validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def admin
    render layout: 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def math
    @numbers = (1..46).to_a.sample(6)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
    def nav_li text, path
        active = request.path == path ? :active : nil
        content_tag :li, link_to(text, path), class: active
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/admin.html.erb
<h1>Admin#admin</h1>
<p>Find me in app/views/admin/admin.html.erb</p>

app/views/layouts/admin.html.erb
<html>
    <head>
    </head>
        <title>後台</title>
        <%= stylesheet_link_tag 'admin' %>
        <%= javascript_include_tag 'admin' %>

    <body>
        <h1>後台</h1><hr>
        <%= yield %>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar', line_number: 3 %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>關於本站</h1>
<h2>歡迎!<%= params[:name] %></h2>

app/views/pages/form.html.erb
<%= form_tag about_path do %>
    <%= text_field_tag :name %>

    <%= submit_tag %>
<% end %>

app/views/pages/home.html.erb
<h1>歡迎來到首頁</h1>
<h2>關於本站</h2>

app/views/pages/math.html.erb
<ul>
<% @numbers.each do |i| %>
    <li><%= i %></li>
<% end %>
</ul>

app/views/shared/_navbar.html.erb
<ul>
 <%= nav_li "首頁", root_path %>
 <%= nav_li "關於", about_path %>
 <%= nav_li "樂透", math_path %>
 <%= nav_li "表單", form_path %>
 </ul> 
<% line_number.times do %>
<hr>
<% end %> 